url: https://michaelbornvo.com
baseurl: /

# Site settings
title: Michael Born Voice-Overs
email: info@michaelbornvo.com
description: "Michael Born Voice-Overs"


# Team names, titles and social links
people:
- name: Michael Born
  pic: 1
  position: Owner, Voice-Over Talent
  social:
    - title: twitter
      url: https://twitter.com/michaelbornvo
    - title: facebook
      url: https://facebook.com/michaelbornvo
    - title: linkedin
      url: https://www.linkedin.com/in/michael-born-890080324


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/michaelbornvo
  - title: facebook
    url: https://facebook.com/michaelbornvo
  - title: linkedin
    url: https://www.linkedin.com/in/michael-born-89080324/
  - title: backstage
    url: https://www.backstage.com/u/michael-born
  - title: voices123
    url: https://voice123.com/michaelborn

# Postal address (add as many lines as necessary)
address:
  - line: P.O. Box 205
  - line: Bennington, NE 68007

# Build settings
markdown: kramdown
permalink: pretty